- name: "Provision WP Database"
  mysql_db: name="{{ db }}" state=present

- name: "Grant WP user access to WP DB"
  mysql_user: name="{{ db_user }}" priv="{{ db }}.*:ALL" host="%" password={{ db_user_password }} state=present

- name: "Grant WP user access to WP DB"
  mysql_user: name="{{ db_user }}" priv="{{ db }}.*:ALL" host="localhost" password={{ db_user_password }} state=present

- name: "Set up docroot"
  file: path={{ wp_doc_root }}/{{ inventory_hostname }} state=directory owner={{ web_user }} group={{ web_group }}

- name: "Set up virtualhosts"
  template: src=etc/nginx/hhvm.conf.j2 dest=/etc/nginx/sites-available/{{ inventory_hostname }}

- name: "Enable {{ enviro }} virtualhosts"
  file: src=/etc/nginx/sites-available/{{ inventory_hostname }} dest=/etc/nginx/sites-enabled/{{ inventory_hostname }} state=link
  notify: nginx reload

- name: "Ensure WordPress directory exists"
  stat: path="{{ wp_doc_root }}/{{ inventory_hostname }}/wp-content"
  register: "wp_dir"

- name: "Download and install WordPress for {{ enviro }}"
  command: /usr/local/bin/wp core download --path={{ wp_doc_root}}/{{ inventory_hostname }}
  sudo: yes
  sudo_user: "{{ web_user }}"
  register: command_result
  when: wp_dir.stat.exists == False

- name: "Ensure WordPress config exists"
  stat: path="{{ wp_doc_root }}/{{ inventory_hostname }}/wp-config.php"
  register: "wp_conf"

- name: "Fetch random salts for WordPress config"
  local_action: command curl https://api.wordpress.org/secret-key/1.1/salt/
  register: "wp_salt"
  sudo: no
  when: wp_conf.stat.exists == False

- name: "Create wp-config for {{ enviro }}"
  template: src=wp/wp-config.php.j2 dest={{ wp_doc_root }}/{{ inventory_hostname }}/wp-config.php owner={{ web_user }} group={{ web_group }}
  when: wp_conf.stat.exists == False

- name: "Localconfig for {{ enviro }} WordPress"
  template: src=wp/local-config.php.j2 dest={{ wp_doc_root }}/{{ inventory_hostname }}/local-config.php owner={{ web_user }} group={{ web_group }}

- name: "Object Cache for {{ enviro }} WordPress"
  template: src=wp/object-cache.php.j2 dest={{ wp_doc_root }}/{{ inventory_hostname }}/wp-content/object-cache.php owner={{ web_user }} group={{ web_group }}

- name: "Run the WP install for {{ enviro }}"
  command: chdir={{ wp_doc_root }}/{{ inventory_hostname }} /usr/local/bin/wp core install --url={{ inventory_hostname }} --title="{{ wp_site_name }}" --admin_user={{ wp_admin }} --admin_password={{ wp_admin_password }} --admin_email="admin@example.com"
  sudo: yes
  sudo_user: "{{ web_user }}"
  register: command_result
  changed_when: not "'WordPress files seem to already be present here.' in command_result.stderr"