---
- name: Create swap file
  command: fallocate -l 2G /swapfile
  when: ansible_swaptotal_mb < 2046

- name: Setup swap area
  command: mkswap /swapfile
  when: ansible_swaptotal_mb < 2046

- name: Change swap file permissions
  file: path=/swapfile
        owner=root
        group=root
        mode=0600
  when: ansible_swaptotal_mb < 2046

- name: Write swap entry in fstab
  mount: name=none
         src=/swapfile
         fstype=swap
         opts=sw
         passno=0
         dump=0
         state=present
  when: ansible_swaptotal_mb < 2046

- name: Swap on
  command: swapon /swapfile
  when: ansible_swaptotal_mb < 2046
